# Generated by Django 5.1.6 on 2025-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата первой отправки')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания отправки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('successful_attempts', models.IntegerField(default=0)),
                ('unsuccessful_attempts', models.IntegerField(default=0)),
                ('sent_messages', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-end_time'],
                'permissions': [('can_disable_mailing', 'Can disable mailing')],
            },
        ),
        migrations.CreateModel(
            name='CampaignAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('status_ok', 'Успешно'), ('status_nok', 'Не успешно')], max_length=15, verbose_name='Статус попытки')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['date_attempt', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['topic'],
            },
        ),
    ]
